### ISSUE TITLE
This should be tested in 0.10-6.x

### ISSUE THREAD

**Issue by isiahmeadows** [substack/node-resolve#108]
Currently, both versions this is tested on in Travis (0.6 and 0.8) are unsupported, even in maintenance mode. Could this be instead tested in 0.10, 0.12, 4, 5, and 6 (all the currently supported versions)?

@substack I believe this might unmask many of the errors people are experiencing with this project.

**Comment by ljharb** [comment]
Fixed in 1f7aa376bcf5d1a5a9580fdf0c4925d505938ff1
