### ISSUE TITLE
Error.code is undefined

### ISSUE THREAD

**Issue by steelbrain** [substack/node-resolve#115]
Steps to repro

```
$ mkdir -p /tmp/resolve-bug
$ cd $_
$ echo '{}' > package.json
$ npm install resolve@latest
$ node
> require('resolve')('asd', function(error) { console.log(error.code, error.message) })
```

Expected behavior:

```
MODULE_NOT_FOUND 'Cannot find module \'asd\' from \'.\''
```

Current behavior:

```
undefined 'Cannot find module \'asd\' from \'.\''
```

I'm on resolve@1.2.0 on macOS
I did search through existing issues to make sure this wasn't a duplicate

**Comment by ljharb** [comment]
This was added in #81 / https://github.com/substack/node-resolve/commit/c622aefeb286e479d536601e30bb828e69f86ec3, and has not yet been released. The Github interface erroneously shows it as landing in 2015, when in fact it was added between dd506158089f7d071d2a9f61cd4385365d177219 and 6984dcb1407fec6af46f744ad2c63f502645bdd6.

**Comment by steelbrain** [comment]
Thank you, looking forward to the new release
