### ISSUE TITLE
core included modules not correct on node 6.9.0

### ISSUE THREAD

**Issue by mlucool** [substack/node-resolve#117]
It seems the algo for `core` is not working as expected on node 6.9.0:

`test.js`:
```
const core = require('resolve/lib/core.js');
console.log('Current version %s', process.versions.node);
console.log('path: %s', core['path']);
console.log('v8: %s', core['v8']);
console.log('process: %s', core['process']);
```

Output:
```
node test.js 
Current version 6.9.0
path: true
v8: undefined
process: undefined
```

**Comment by ljharb** [comment]
Which version of `resolve` do you have installed?

**Comment by mlucool** [comment]
Good catch, closing. Issue is eslint isn't using the latest version: https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/node/package.json#L29
