### ISSUE TITLE
Node modules path dirs resolver bug

### ISSUE THREAD

**Issue by bruno12mota** [substack/node-resolve#118]
Hey guys!

I've recently came across a problem when using jest that uses node-resolver to resolve the dependencies. The problem is detailed here https://github.com/facebook/jest/issues/2947

Anyway I've debug it throughout and came to the conclusion the problem was with node-resolver itself as you can see from the issue in jest. I've looked into the master branch here and tried replacing the changed node-modules-path file and the problem was fixed. From this commit actually https://github.com/substack/node-resolve/commit/58b99a36f882d7ee65df725224f204abd27379db

So anyway you guys can release this so this can be fixed? I just checked that the last release was before this fix.

Thanks!

**Comment by bruno12mota** [comment]
Any way to have the master released to 1.2.1? Is there any work left to allow that?

**Comment by ljharb** [comment]
v1.3.0 is released.

**Comment by bruno12mota** [comment]
Thanks Jordan!
