### ISSUE TITLE
Broken in browserify

### ISSUE THREAD

**Issue by sabrehagen** [substack/node-resolve#120]
[This commit](https://github.com/substack/node-resolve/commit/c2cbdddcc2aa1c427ccd8a7c1784c745093f836f#diff-f265d6a6b6b64d4d096fddcf7d620a76R1) broke node-resolve being able to be used with browserify. `process.versions` is an empty object when this code runs in the browser, and the `node` key does not exist.

Running `npm start` in [this project](https://github.com/yoshuawuyts/choo/tree/master/examples/mailbox) can be used to reproduce the error.

**Comment by ljharb** [comment]
Thanks, good catch! I'll fix and release an update today in both the v1.2 and v1.3 lines.

**Comment by ljharb** [comment]
v1.2.1 and v1.3.2 published.
