### ISSUE TITLE
Can throw ENOTDIR instead of MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by loganfsmyth** [substack/node-resolve#121]
```
require('./CHANGELOG.md/directory');
```
will throw code `MODULE_NOT_FOUND`, but

```
require('resolve').sync('./CHANGELOG.md/directory')
```

will throw code `ENOTDIR`.

**Comment by ljharb** [comment]
The comparison would be to `require.resolve`, not to `require`, but I suspect that's a red herring.

What filesystem setup and `resolve` version are you getting `ENOTDIR` with? I can't reproduce it - everything gives me `MODULE_NOT_FOUND`.

**Comment by loganfsmyth** [comment]
Right, true enough about the example.

My setup was just in the root of the Babel repo, in this case with `CHANGELOG.md` being a file in the current directory. Should reproduce in a empty dir with

    touch CHANGELOG.md
    node -e "require('resolve').sync('./CHANGELOG.md/directory')"

**Comment by ljharb** [comment]
Thanks, with a filename that exists, I get the following:
```
> try { require('./').sync('./FILENAME/'); } catch (e) { e.code; }
'$PWD/FILENAME'

> try { require('./').sync('./FILENAME/dir'); } catch (e) { e.code; }
'ENOTDIR'
```

`require.resolve`, in both cases, gives `MODULE_NOT_FOUND`.

The former is a bug, the latter is a deviation (arguably a more useful variant) - but since `require.resolve` doesn't do that, we shouldn't either.

**Comment by ljharb** [comment]
Of note, this seems to only happen when the `basedir` option is not provided.

**Comment by loganfsmyth** [comment]
I first ran across it when using a `basedir`, but it appears to happen with or without for me.

**Comment by ljharb** [comment]
@loganfsmyth could you give [this branch](https://github.com/ljharb/node-resolve/tree/fix_api_differences) a try? It includes both a fix, and a (hopefully insignificant) breaking change, which should bring `resolve` in line with `require.resolve` for these kinds of scenarios.

**Comment by loganfsmyth** [comment]
Looks good to me, thanks! Sorry it took so long to get back to this.

**Comment by ljharb** [comment]
@loganfsmyth thanks!
