### ISSUE TITLE
Absolute paths don't take opts.extensions into account

### ISSUE THREAD

**Issue by thymikee** [substack/node-resolve#127]
It seems like passing `extensions` in `opts` when calling `resolve(path, opts)` don't work when provided `path` is absolute. 

See https://github.com/facebook/jest/issues/3342 for description and "repro" (I'll try to provide something easier to debug later).

**Comment by ljharb** [comment]
Thanks - with a simpler repro case (ideally, a failing test or two), I can get a fix for this out ASAP.

**Comment by thymikee** [comment]
Closing, after deeper debugging while writing a test for it, turned out to be an internal Jest thing. Thanks anyway! :)
