### ISSUE TITLE
Use the real path for resolving dependencies

### ISSUE THREAD

**Issue by zkochan** [substack/node-resolve#130]
Node uses the real path of modules (except when executed with `--preserve-symlinks`) to resolve dependencies. That is why [pnpm](https://github.com/pnpm/pnpm)'s [symlinked `node_modules`](https://github.com/pnpm/pnpm/blob/master/docs/symlinked-node-modules-structure.md) work fine with Node applications.

However, `resolve` is a really popular and widely used package and it does not use the real path of modules to resolve dependencies. As a consequence, a lot of tooling fails with pnpm. See the most recent issue: https://github.com/pnpm/pnpm/issues/857. And also many of these might be related: https://github.com/pnpm/pnpm/issues/801

Would you accept a pull request to change the behavior of `resolve` to work the way Node does? It won't change anything for projects that use npm/Yarn because they don't leverage symlinks but it would be a **huge** help for the pnpm community!

**Comment by ljharb** [comment]
Sure, that sounds good - let's ensure that a) existing tests keep passing (ofc), b) we add a "preserve symlinks" option, so users can control the behavior if they like, and c) let's think carefully about if it's possible to avoid a semver-major.

**Comment by malash** [comment]
@zkochan Did you forget to change this condition when resolving real path for `basedir` ?

https://github.com/browserify/resolve/blob/fed3f0fb1eee4e44655b572dc183b6eef8bf44e1/lib/sync.js#L29

E.g. this line may fail `require('resolve').sync('../../path/to/another/package', { basedir: '/path/to/a/symlink' })`.

FYI @ljharb

**Comment by ljharb** [comment]
@malash could you file a separate issue for that, with a test case?

**Comment by malash** [comment]
I'v create a new issue with bad case example https://github.com/browserify/resolve/issues/177
