### ISSUE TITLE
Dependency with 'cloneWithProps'

### ISSUE THREAD

**Issue by ArtanisAce** [substack/node-resolve#133]
Hi, recently I've upgraded my project from React 0.14 to 15, and as you might know, on this last version 'cloneWithProps' is deprecated and you must use 'cloneElement' instead. Well, browserify install 'module-deps' as a dependency, and this one installs 'browser-resolve', which installs 'resolve' and this one needs 'react-addons-clone-with-props'. Is there a way to fix this? I can't see where in 'lib/async.js' in the module is using 'cloneWithProps'. I'm banging my head as I have been searching around and nobody had the same problem...

This is the output of my gulp build:
`Error: Cannot find module 'react/lib/cloneWithProps' from '/home/ppmiron/Development/Project/node_modules/react-addons-clone-with-props' at /home/ppmiron/Development/Project/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17 at process (/home/ppmiron/Development/Project/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43) at ondir (/home/ppmiron/Development/Project/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17) at load (/home/ppmiron/Development/Project/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43) at onex (/home/ppmiron/Development/Project/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31) at /home/ppmiron/Development/Project/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47 at FSReqWrap.oncomplete (fs.js:82:15)`

**Comment by ljharb** [comment]
I'm not sure where you're seeing `react-addons-clone-with-props`; this module has only [one dependency](https://github.com/substack/node-resolve/blob/master/package.json).

Your stack trace indicates that browserify is simply using `resolve` to resolve the path of that module; not that `resolve` is the thing bringing it in.
