### ISSUE TITLE
Error in async mode and strange benchmark test

### ISSUE THREAD

**Issue by Meettya** [substack/node-resolve#18]
Hi! 
For some reason I write my own require.resolve() implementation and use yours and some other for benchmarking.

So, today I saw async mode in node-resolve and add it to test suite. And its sometime works, and sometime not.

See yourself - add https://github.com/Meettya/node-resolve/commit/04d85e5769434804ffd9bd29072be3c509230032

`npm install node-bench -g`
`npm install lodash`

and run test from root dir (may uncomment assert in async to get error)
`node-bench ./bench/async-resolve_vs_other.js`

and even more - if node-bench right - in my tests sync mode faster than async - its strange.

**Comment by ljharb** [comment]
@Meettya @zxqfox I'm not sure what's actionable here - I'm going to close this for now, but happy to reopen if needed.
