### ISSUE TITLE
resolve silently eats unknown exceptions

### ISSUE THREAD

**Issue by fresheneesz** [substack/node-resolve#33]
There are a couple places where resolve eats exceptions. This is simply not acceptable. This wasted a good 30 minutes of my time, and it could have been much worse. Unknown exceptions _always_ need to be propagated.

In sync.js, exceptions are eaten on the following lines:

12: catch (err) { if (err && err.code === 'ENOENT') return false }
64: catch (err) {}

in async.js:
81: catch (err) {}

**Comment by ljharb** [comment]
#80 took care of this for `resolve.sync`, and it appears that the `async` version currently calls the callback with the error - so I think this is now resolved?
