### ISSUE TITLE
Many failing tests on windows 8.1

### ISSUE THREAD

**Issue by fresheneesz** [substack/node-resolve#52]
I'm on Windows 8.1, node v0.10.29, and _all_ test files have failing asserts except `core.js`.

**Comment by amb26** [comment]
Looks like noone has any care whether this module's test cases pass on Windows or not over these two years. I discovered this whilst trying to make a fix for #106 and found that there's really no point writing a test case to verify my fix. Thanks for issuing #54, @Evgenus , I'll incorporate it into our project's fork.

**Comment by ljharb** [comment]
@fresheneesz can you try rerunning the tests on Windows on latest master?

**Comment by fresheneesz** [comment]
@ljharb Looks like the tests work now!
