### ISSUE TITLE
'Cannot find module` not telling me the "why"

### ISSUE THREAD

**Issue by krainboltgreene** [substack/node-resolve#84]
Turns out the library didn't have the file listed in it's `main` property on `package.json` (due to another reason).

**Comment by nucliweb** [comment]
Yes, the library to import need a `main` property in the `package.json`

**Comment by krainboltgreene** [comment]
That isn't relevant to this issue. The library has a `main` property in `package.json`, but the path is invalid.

**Comment by nucliweb** [comment]
Do you have a repo for see the structure of files and dependencies?

**Comment by ljharb** [comment]
@krainboltgreene I'm not sure what's actionable here - I'm going to close this, but I'm happy to reopen given more information (a repro case, with the error message you'd prefer, would help).
