### ISSUE TITLE
Add support for libs that only contain `jsnext:main` prop in package.json

### ISSUE THREAD

**Issue by caccialdo** [substack/node-resolve#93]
Currently the only way `node-resolve` resolves a package directory is if the related `package.json` file contains a `main` property.

cf. https://github.com/substack/node-resolve/blob/master/lib/async.js#L147

Would be great to support future libs that only contain the `jsnext:main` prop.

**Comment by mgechev** [comment]
With callback `packageFilter` you can set the main property to the value of the `jsnext:main` property.

**Comment by ljharb** [comment]
This is a non-standard package.json field that neither npm nor node supports, and is a very bad idea for bundlers to be supporting.

`resolve` won't be supporting it anything `require` doesn't support.

**Comment by Scimonster** [comment]
Example usage, since `packageFilter` is not well documented:

```js
var resolveSync = require('resolve').sync;
function resolve(pkgName) {
    return resolveSync(pkgName, {
        packageFilter: function(pkg){
            if (pkg.module) {
                pkg.main = pkg.module;
            } else if (pkg['jsnext:main']) {
                pkg.main = pkg['jsnext:main'];
            }
            return pkg;
        }
    })
}
```
