### ISSUE TITLE
`node-modules-paths.js` adds `undefined` as last item to its array.

### ISSUE THREAD

**Issue by cpojer** [substack/node-resolve#96]
`node-modules-paths.js` adds `undefined` as last item to its array. This is probably a bug :)

Repro: nodeModulesPaths(__dirname, {});

**Comment by ljharb** [comment]
This seems to be because the function, which is primarily used internally, unconditionally concats `opts.paths` to the result. If you do `nodeModulesPaths(__dirname, { paths: [] })`, you won't see the `undefined`.

**Comment by cpojer** [comment]
https://github.com/facebook/jest/blob/master/packages/jest-resolve/src/index.js#L201

🤷‍♀️

fyi we are planning on rewriting the sync part of `resolve` for perf (we have an in-memory fs) and will merge it into jest-resolve to be used both by Jest and RNP. That also means we'll finally have a single implementation of a resolution algorithm across FB's tools (except Flow, I guess). Not really important to this issue, but you may care. If you are planning on improving perf of `resolve.sync`, we could also drop this idea and change our in-memory fs to be more `fs`-like.

Even better would be for this module to be rewritten entirely, to be merged into nodejs directly and then exposed as an API.

**Comment by ljharb** [comment]
I'd be happy to improve the perf of `resolve.sync` as long as the observable API didn't change (this `undefined` thing is a bug that will be imminently fixed).
